### ISSUE TITLE
Box-shadow not working

### ISSUE THREAD

**Issue by ArgekarStudios** [windicss/windicss#626] opened 2021-12-26 15:43 UTC
<div class="flex justify-center items-center shadow-2xl shadow-purple-800 px-3 py-5 rounded-full">
      Sign in with Google
    </div>
    
    changing shadow color not working always shows default shadow

**Comment by Techassi** [comment] 2021-12-27 11:29
Please provide a minimal reproduction link so that I can look into it.

**Comment by Techassi** [comment] 2022-02-02 15:37
This seems like a duplicate of #633. Please update to the latest version `3.4.3`

**Closed** 2022-02-03 11:24 UTC
