### ISSUE TITLE
Windicss CLI is not scanning a directory when first parameter is in quotes

### ISSUE THREAD

**Issue by wvffle** [windicss/windicss#282] opened 2021-05-12 19:32 UTC
When my project team member tries to run a command `windicss './src/**/*.html'` which is in our build system, it fails to find any file.
She is working on windows.

When he tries to run it without the quotes it works for her, though on linux the files would be matched only once with bash so we don't want to change that buildscript.

**Comment by voorjaar** [comment] 2021-05-13 04:53
https://github.com/windicss/windicss/commit/750b496d764f6768d1e15d7dfada6c898f716ffe should fixed it.

**Comment by voorjaar** [comment] 2021-05-13 06:31
please update to v3.0.1. If the issue is resolved, close the issue thanks.

**Closed** 2021-05-15 06:10 UTC
